### ISSUE TITLE
Menu item shows on all context menus

### ISSUE THREAD

**Issue by AaronSadlerUK** [NikRimington/HotChilli.Umbraco.PageNotFoundManager#5] opened 2021-09-10 20:32 UTC
**Version**
Umbraco V9 RC3

**Issue**
The "Manage 404 Page" menu item is showing on all context menus

**Expected**
The "Manage 404 Page" menu item should only show on the "Content" context menu

**Comment by NikRimington** [comment] 2021-09-11 20:41
Do you have examples of where you don't think it should be showing? :-)

**Comment by AaronSadlerUK** [comment] 2021-09-12 19:52
Edit Member:
![image](https://user-images.githubusercontent.com/9937803/133000834-5d7bfaba-01f4-4391-8de7-bd52bca53542.png)

Settings -> Templating:
![image](https://user-images.githubusercontent.com/9937803/133000866-b4fe0145-4daf-423c-a35a-aaaf1f65f715.png)

Media:
![image](https://user-images.githubusercontent.com/9937803/133000903-8548c7b6-fb72-4102-94a3-c9025e192eb1.png)

**Comment by NikRimington** [comment] 2021-09-12 19:54
Thanks :-) I "might" know what the problem is and might have it solved, I'll check all those context menus and see.

**Comment by NikRimington** [comment] 2021-09-15 23:45
Hey @AaronSadlerUK , I've got this fixed now. I should have a new beta out shortly :-)

**Comment by NikRimington** [comment] 2021-09-15 23:51
Beta 6 is released to nuget.

**Closed by NikRimington** 2021-09-15 23:51 UTC
